# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20160722_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_friend',
            field=models.BooleanField(default=False),
        ),
    ]
