# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-23 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20160723_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='owner',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='owner',
            field=models.ManyToManyField(related_name='current_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
