# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-23 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_auto_20160723_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='owner',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
