# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-27 01:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20160724_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish', '-updated']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='publish',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Publication date'),
        ),
    ]
