# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-29 00:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation date'),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
